### ISSUE TITLE
[BUG] crashing upon startup

### ISSUE THREAD

**Issue by njuff22** [28Pollux28/ImageWorldGenerator#18]
Caused by: java.lang.ClassNotFoundException: dev.onyxstudios.cca.api.v3.world.WorldComponentInitializer
		at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
		at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
		at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
		at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
		at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:168)
		at java.lang.ClassLoader.loadClass(ClassLoader.java:357)

mods being used:
ImageWorldGenerator
Fabric API 
Oh the biomes you'll go

attached files:
full crash report
imggen.json - converted to .txt for the sake of uploading to github

[crash-2021-05-12_09.24.29-client.txt](https://github.com/28Pollux28/ImageWorldGenerator/files/6464230/crash-2021-05-12_09.24.29-client.txt)

[imggen - Copy.txt](https://github.com/28Pollux28/ImageWorldGenerator/files/6464238/imggen.-.Copy.txt)

**Comment by 28Pollux28** [comment]
Ok so from what I can see your imogen.json is not correct. There are a couple commas missing leading to this issue.

**Comment by njuff22** [comment]
[imggen.txt](https://github.com/28Pollux28/ImageWorldGenerator/files/6469123/imggen.txt)
adding a comma to line 603 makes it start, but generates a random world;
removing the comma triggers a syntax error around line 603-604

**Comment by 28Pollux28** [comment]
What do you mean when you say "generates a random world" ? Would it be possible for you to send me the log.txt file ?

**Comment by njuff22** [comment]
feel like a fucking idiot. Oceans i had used were the incorrect color

**Comment by 28Pollux28** [comment]
Np, glad this is resolved. By the way I believe you're grenadeboo from curseforge. Would you mind deleting that comment as I would like this space just to be about comments/questions, not issues.
